
package nswi145;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-03-20T19:02:53.885+01:00
 * Generated source version: 3.5.5
 */

@WebFault(name = "Exception", targetNamespace = "http://nswi145/")
public class Exception_Exception extends java.lang.Exception {

    private nswi145.Exception faultInfo;

    public Exception_Exception() {
        super();
    }

    public Exception_Exception(String message) {
        super(message);
    }

    public Exception_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, nswi145.Exception exception) {
        super(message);
        this.faultInfo = exception;
    }

    public Exception_Exception(String message, nswi145.Exception exception, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = exception;
    }

    public nswi145.Exception getFaultInfo() {
        return this.faultInfo;
    }
}
