
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package nswi145;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-03-20T19:02:53.889+01:00
 * Generated source version: 3.5.5
 *
 */

@javax.jws.WebService(
                      serviceName = "MapServiceImplService",
                      portName = "MapServiceImplPort",
                      targetNamespace = "http://nswi145/",
                      wsdlLocation = "http://127.0.0.1:8000/Map?wsdl",
                      endpointInterface = "nswi145.MapService")

public class MapServiceImplPortImpl implements MapService {

    private static final Logger LOG = Logger.getLogger(MapServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see nswi145.MapService#uploadMap(nswi145.Map map, int id)*
     */
    public nswi145.MapUploadResult uploadMap(nswi145.Map map, int id) {
        LOG.info("Executing operation uploadMap");
        System.out.println(map);
        System.out.println(id);
        try {
            nswi145.MapUploadResult _return = new nswi145.MapUploadResult();
            _return.setOK(false);
            _return.setId(677336959);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see nswi145.MapService#approveMap(int id, int userId)*
     */
    public void approveMap(int id, int userId) throws Exception_Exception   {
        LOG.info("Executing operation approveMap");
        System.out.println(id);
        System.out.println(userId);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

}
