
package nswi145;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-03-20T19:02:53.854+01:00
 * Generated source version: 3.5.5
 *
 */
public final class MapService_MapServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://nswi145/", "MapServiceImplService");

    private MapService_MapServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MapServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        MapServiceImplService ss = new MapServiceImplService(wsdlURL, SERVICE_NAME);
        MapService port = ss.getMapServiceImplPort();

        {
        System.out.println("Invoking uploadMap...");
        nswi145.Map _uploadMap_map = new nswi145.Map();
        _uploadMap_map.setName("Name307941993");
        int _uploadMap_id = -1899597112;
        nswi145.MapUploadResult _uploadMap__return = port.uploadMap(_uploadMap_map, _uploadMap_id);
        System.out.println("uploadMap.result=" + _uploadMap__return);


        }
        {
        System.out.println("Invoking approveMap...");
        int _approveMap_id = -601855476;
        int _approveMap_userId = -7516593;
        try {
            port.approveMap(_approveMap_id, _approveMap_userId);

        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }

            }

        System.exit(0);
    }

}
