package nswi145;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-03-20T19:02:53.897+01:00
 * Generated source version: 3.5.5
 *
 */
@WebServiceClient(name = "MapServiceImplService",
                  wsdlLocation = "http://127.0.0.1:8000/Map?wsdl",
                  targetNamespace = "http://nswi145/")
public class MapServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://nswi145/", "MapServiceImplService");
    public final static QName MapServiceImplPort = new QName("http://nswi145/", "MapServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8000/Map?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MapServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8000/Map?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MapServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MapServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MapServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public MapServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MapServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MapServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns MapService
     */
    @WebEndpoint(name = "MapServiceImplPort")
    public MapService getMapServiceImplPort() {
        return super.getPort(MapServiceImplPort, MapService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MapService
     */
    @WebEndpoint(name = "MapServiceImplPort")
    public MapService getMapServiceImplPort(WebServiceFeature... features) {
        return super.getPort(MapServiceImplPort, MapService.class, features);
    }

}
