
package userservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.5
 * Mon Mar 20 16:45:29 CET 2023
 * Generated source version: 3.5.5
 */

@XmlRootElement(name = "getPendingMapsResponse", namespace = "http://userservice/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getPendingMapsResponse", namespace = "http://userservice/")

public class GetPendingMapsResponse {

    @XmlElement(name = "return")
    private int _return;

    public int getReturn() {
        return this._return;
    }

    public void setReturn(int new_return)  {
        this._return = new_return;
    }

}

